Poista testutilseista virheen aiheuttava require
Testit alkoivat failaamaan tällaisella viestillä:

TypeError: null is not an object (evaluating 'getReactDOM().__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED')

  phantomjs://code/phantom1110046519965715849.js:74 in onError

Virhettä ei tule, kun cljs-react-test.utils kirjaston requiren
poistaa harjan testutilseista. Jännittävästi kyseinen kirjasto ei
aiheuta ongelmia harjan sharerd-testutilseissa.

En alkanut tätä sen kummemmin debuggaamaan, koska kirjastoa ei
edes testutilseissa käytetä.